name: Deploy to Main Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
          coverage: none
    
    - name: Install Composer Dependencies
        run: composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader

    - name: Install NPM Dependencies
        run: npm install
    - name: Build Frontend Assets
        run: npm run build
        env:
          VITE_APP_URL: https://ordinance.nnterp.com
    
    - name: Deploy to Main Server via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd /home/nnterp.com/ordinance
          git config --global --add safe.directory /home/nnterp.com/ordinance
          git reset --hard
          git clean -fd
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git pull https://${{ secrets.GIT_TOKEN }}@github.com/dvappnnt/legal_ai.git main

          rm -rf node_modules package-lock.json
          composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader
          npm install
          npm run build

          php artisan down
          echo "Application in maintenance mode: Deploying new version..."
          
          php artisan migrate --force
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache

          php artisan cache:clear
          php artisan config:clear
          php artisan view:clear

          chmod -R 775 storage bootstrap/cache
          chown -R daemon:daemon storage bootstrap/cache
          chmod -R 777 /home/nnterp.com/ordinance/storage /home/nnterp.com/ordinance/bootstrap/cache
          php artisan up
          echo "Deployment completed successfully"